export enum BookingActionType {
  START_LOAD_INVITATION = "START_LOAD_INVITATION",
  END_LOAD_INVITATION = "END_LOAD_INVITATION",
  SET_INVITATION = "SET_INVITATION",
  SET_ADMIN_INVITATION = "SET_ADMIN_INVITATION",
  SET_BOOKING = "SET_BOOKING",
  UPDATE_BOOKING = "UPDATE_INVITATION",
}
