export enum BookingActionType {
  START_LOAD_INVITATION = "START_LOAD_INVITATION",
  ADD_BOOKING = "ADD_BOOKING",
  GET_MOMENT = "GET_MOMENT",
  SET_MOMENT = "SET_MOMENT",
  END_LOAD_INVITATION = "END_LOAD_INVITATION",
  SET_INVITATION = "SET_INVITATION",
  SET_ADMIN_INVITATION = "SET_ADMIN_INVITATION",
  SET_BOOKING = "SET_BOOKING",
  SET_BOOKING_RESPONSE = "SET_BOOKING_RESPONSE",
  UPDATE_BOOKING = "UPDATE_INVITATION",
}
