export enum BookingActionType {
  START_LOAD_INVITATION = "START_LOAD_INVITATION",
  END_LOAD_INVITATION = "END_LOAD_INVITATION",
  SET_INVITATION = "SET_INVITATION",
  SET_BOOKING = "SET_BOOKING",
}
