export enum RestaurantActionType {
  START_LOAD_RESTAURANT = "START_LOAD_RESTAURANT",
  START_FETCH_RESTAURANT = "START_FETCH_RESTAURANT",
  SET_RESTAURANT_LIST = "SET_RESTAURANT_LIST",
  UPLOAD_RESTAURANT_FILE = "UPLOAD_RESTAURANT_FILE",
  END_LOAD_RESTAURANT = "END_LOAD_RESTAURANT",
  END_FETCH_RESTAURANT = "END_FETCH_RESTAURANT",
}
